all: part1 part2 assign1 assign2

part1: part1.cpp
	g++ -g -Wall -std=c++11 $^ -o $@

part2: part2.cpp
	g++ -g -Wall -std=c++11 $^ -o $@

assign1: assign1.cpp
	g++ -g -Wall -std=c++11 $^ -o $@

assign2: assign2.cpp
	g++ -g -Wall -std=c++11 $^ -o $@

clean:
	rm -f part1 part2 assign1 assign2